In [51]:
import pandas as pd
import numpy as np

In [61]:
# Корреляция целевой переменной price_range с каждым признаком
df.drop("price_range", axis=1).apply(lambda x: x.corr(df['price_range']))

battery_power    0.149402
blue             0.014001
clock_speed      0.003494
dual_sim         0.009002
fc               0.022464
four_g           0.001001
int_memory       0.022132
m_dep           -0.018554
mobile_wt       -0.007968
n_cores          0.031260
pc               0.027628
px_height        0.097951
px_width         0.116703
ram              0.822354
sc_h             0.009140
sc_w             0.035359
talk_time        0.004394
three_g          0.024638
touch_screen    -0.040001
wifi             0.014001
dtype: float64

In [42]:
signs

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,842,0,2.2,0,1,0,7,0.6,188,2,2,20,756,2549,9,7,19,0,0,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0
2,563,1,0.5,1,2,1,41,0.9,145,5,6,1263,1716,2603,11,2,9,1,1,0
3,615,1,2.5,0,0,0,10,0.8,131,6,9,1216,1786,2769,16,8,11,1,0,0
4,1821,1,1.2,0,13,1,44,0.6,141,2,14,1208,1212,1411,8,2,15,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,14,1222,1890,668,13,4,19,1,1,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,3,915,1965,2032,11,10,16,1,1,1
1997,1911,0,0.9,1,1,1,36,0.7,108,8,3,868,1632,3057,9,1,5,1,1,0
1998,1512,0,0.9,0,4,1,46,0.1,145,5,5,336,670,869,18,10,19,1,1,1
1999,510,1,2.0,1,5,1,45,0.9,168,6,16,483,754,3919,19,4,2,1,1,1

In [44]:
corr_matrix = np.corrcoef(signs, target)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 20 and the array at index 1 has size 1

In [40]:
target

      price_range
0               0
1               1
2               1
3               1
4               0
...           ...
1995            0
1996            1
1997            1
1998            0
1999            1

[2000 rows x 1 columns]

In [41]:
signs = df.drop('price_range', axis=1)

Теперь необходимо обучить алгоритм.  Для начала разбейте выборку на тестовую и обучающую, размер тестовой задайте 0.2. Параметр random_state=31. В качестве модели возьмите логистическую регрессию. В качестве предикторов возьмите пять ранее отобранных признаков.
Рассчитайте метрику, которая покажет, какая доля телефонов, обозначенных классификатором как дорогие, действительно относится к этой категории.

In [62]:
from sklearn.linear_model import LogisticRegression # наша модель для классификации
from sklearn.model_selection import train_test_split # функция, чтобы разбить данные на трейн и тест

In [63]:
Y = df[['price_range']] ## Наша целевая переменная
X = df[['battery_power', 'px_height', 'px_width', 'ram', 'touch_screen']] # X - признаки

In [64]:
X_train, X_val, Y_train, Y_val = train_test_split(X, Y, test_size = 0.2, random_state=31)
model = LogisticRegression()
model.fit(X_train, Y_train)

/home/ramory-l/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

LogisticRegression()

In [66]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

Y_predicted = model.predict(X_val)
print(accuracy_score(Y_val,Y_predicted))
print(precision_score(Y_val,Y_predicted))
print(recall_score(Y_val,Y_predicted))
print(f1_score(Y_val,Y_predicted))

0.9875
0.9859154929577465
0.9905660377358491
0.9882352941176472